module.exports = {
	Application: require('./application'),
	AuditLog: require('./auditlog'),
	Channel: require('./channel'),
	Emoji: require('./emoji'),
	Guild: require('./guild'),
	Invite: require('./invite'),
	Member: require('./member'),
	Message: require('./message'),
	Overwrite: require('./overwrite'),
	Presence: require('./presence'),
	Profile: require('./profile'),
	ProfileConnectedAccount: require('./profileconnectedaccount'),
	Reaction: require('./reaction'),
	Relationship: require('./relationship'),
	Role: require('./role'),
	User: require('./user'),
	UserExtended: require('./userextended'),
	UserMe: require('./userme'),
	UserSettings: require('./usersettings'),
	VoiceConnection: require('./voiceconnection'),
	VoiceState: require('./voicestate'),
	Webhook: require('./webhook')
};