name: Deploy docs to Github Pages
on:
  push:
    branches:
      - master
  release:
    branches:
      - master
  workflow_dispatch:
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: git clone https://github.com/detritusjs/utils.git
      - run: git clone https://github.com/detritusjs/rest.git
      - run: git clone https://github.com/detritusjs/client-socket.git
      - run: git clone https://github.com/detritusjs/client-rest.git
      - run: npm run ts-docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs
